const FILELIST_PSLIB_USPP = """
Ag.pbe-dn-rrkjus_psl.0.1.UPF
Al.pbe-n-rrkjus_psl.0.1.UPF
Ar.pbe-n-rrkjus_psl.0.3.0.UPF
As.pbe-n-rrkjus_psl.0.2.UPF
Au.pbe-dn-rrkjus_psl.0.3.0.UPF
Be.pbe-n-rrkjus_psl.0.2.UPF
Bi.pbe-dn-rrkjus_psl.0.2.2.UPF
B.pbe-n-rrkjus_psl.0.1.UPF
Br.pbe-n-rrkjus_psl.0.2.UPF
Cd.pbe-dn-rrkjus_psl.0.3.1.UPF
Cl.pbe-n-rrkjus_psl.0.3.0.UPF
C.pbe-n-rrkjus_psl.0.1.UPF
Cu.pbe-dn-rrkjus_psl.0.2.UPF
Fe.pbesol-spn-rrkjus_psl.0.2.1.UPF
Fe.pbe-spn-rrkjus_psl.0.2.1.UPF
F.pbe-n-rrkjus_psl.0.1.UPF
Ga.pbe-dn-rrkjus_psl.0.2.UPF
Ge.pbe-dn-rrkjus_psl.0.3.1.UPF
Hg.pbe-dn-rrkjus_psl.0.2.2.UPF
H.pbe-rrkjus_psl.0.1.UPF
In.pbe-dn-rrkjus_psl.0.2.2.UPF
I.pbe-n-rrkjus_psl.0.2.UPF
Ir.pbe-n-rrkjus_psl.0.2.3.UPF
Li.pbe-s-rrkjus_psl.0.2.1.UPF
Mo.pbe-spn-rrkjus_psl.0.3.0.UPF
Na.pbe-spn-rrkjus_psl.0.2.UPF
Nb.pbe-spn-rrkjus_psl.0.3.0.UPF
Ni.pbe-n-rrkjus_psl.0.1.UPF
N.pbe-n-rrkjus_psl.0.1.UPF
O.pbe-n-rrkjus_psl.0.1.UPF
Pb.pbe-dn-rrkjus_psl.0.2.2.UPF
Pd.pbe-n-rrkjus_psl.0.3.0.UPF
P.pbe-n-rrkjus_psl.0.1.UPF
Pt.pbe-n-rrkjus_psl.0.1.UPF
Rh.pbe-spn-rrkjus_psl.0.3.0.UPF
Sc.pbe-spn-rrkjus_psl.0.2.3.UPF
Se.pbe-n-rrkjus_psl.0.2.UPF
Si.pbe-n-rrkjus_psl.0.1.UPF
Sn.pbe-dn-rrkjus_psl.0.2.UPF
S.pbe-n-rrkjus_psl.0.1.UPF
Sr.pbe-spn-rrkjus_psl.0.2.3.UPF
Ta.pbe-spn-rrkjus_psl.0.2.UPF
Tc.pbe-spn-rrkjus_psl.0.3.0.UPF
Te.pbe-dn-rrkjus_psl.0.3.1.UPF
Tl.pbe-dn-rrkjus_psl.0.2.3.UPF
Y.pbe-spn-rrkjus_psl.0.2.3.UPF
Zn.pbe-dn-rrkjus_psl.0.2.2.UPF
Zr.pbe-spn-rrkjus_psl.0.2.3.UPF
"""
