const FILELIST_GBRV_LDA = """
ag_lda_v1.4.uspp.F.UPF
al_lda_v1.uspp.F.UPF
as_lda_v1.uspp.F.UPF
au_lda_v1.uspp.F.UPF
ba_lda_v1.uspp.F.UPF
be_lda_v1.4.uspp.F.UPF
b_lda_v1.4.uspp.F.UPF
br_lda_v1.4.uspp.F.UPF
ca_lda_v1.uspp.F.UPF
cd_lda_v1.uspp.F.UPF
c_lda_v1.2.uspp.F.UPF
cl_lda_v1.4.uspp.F.UPF
co_lda_v1.2.uspp.F.UPF
cr_lda_v1.5.uspp.F.UPF
cs_lda_v1.uspp.F.UPF
cu_lda_v1.2.uspp.F.UPF
fe_lda_v1.5.uspp.F.UPF
f_lda_v1.4.uspp.F.UPF
ga_lda_v1.4.uspp.F.UPF
ge_lda_v1.4.uspp.F.UPF
hf_lda_plus4_v1.uspp.F.UPF
hf_lda_v1.uspp.F.UPF
hg_lda_v1.uspp.F.UPF
h_lda_v1.4.uspp.F.UPF
i_lda_v1.uspp.F.UPF
in_lda_v1.4.uspp.F.UPF
ir_lda_v1.2.uspp.F.UPF
k_lda_v1.4.uspp.F.UPF
la_lda_v1.uspp.F.UPF
li_lda_v1.4.uspp.F.UPF
mg_lda_v1.4.uspp.F.UPF
mn_lda_v1.5.uspp.F.UPF
mo_lda_v1.uspp.F.UPF
na_lda_v1.5.uspp.F.UPF
nb_lda_v1.uspp.F.UPF
ni_lda_v1.4.uspp.F.UPF
n_lda_v1.2.uspp.F.UPF
o_lda_v1.2.uspp.F.UPF
os_lda_v1.2.uspp.F.UPF
pb_lda_v1.uspp.F.UPF
pd_lda_v1.4.uspp.F.UPF
p_lda_v1.5.uspp.F.UPF
pt_lda_v1.4.uspp.F.UPF
rb_lda_v1.uspp.F.UPF
re_lda_v1.2.uspp.F.UPF
rh_lda_v1.4.uspp.F.UPF
ru_lda_v1.2.uspp.F.UPF
sb_lda_v1.4.uspp.F.UPF
sc_lda_v1.uspp.F.UPF
se_lda_v1.uspp.F.UPF
si_lda_v1.uspp.F.UPF
s_lda_v1.4.uspp.F.UPF
sn_lda_v1.4.uspp.F.UPF
sr_lda_v1.uspp.F.UPF
ta_lda_v1.uspp.F.UPF
tc_lda_v1.uspp.F.UPF
te_lda_v1.uspp.F.UPF
ti_lda_v1.4.uspp.F.UPF
tl_lda_v1.2.uspp.F.UPF
v_lda_v1.4.uspp.F.UPF
w_lda_v1.2.uspp.F.UPF
y_lda_v1.4.uspp.F.UPF
zn_lda_v1.uspp.F.UPF
zr_lda_v1.uspp.F.UPF
"""


const FILELIST_GBRV_PBE = """
ag_pbe_v1.4.uspp.F.UPF
al_pbe_v1.uspp.F.UPF
as_pbe_v1.uspp.F.UPF
au_pbe_v1.uspp.F.UPF
ba_pbe_v1.uspp.F.UPF
be_pbe_v1.4.uspp.F.UPF
b_pbe_v1.4.uspp.F.UPF
br_pbe_v1.4.uspp.F.UPF
ca_pbe_v1.uspp.F.UPF
cd_pbe_v1.uspp.F.UPF
cl_pbe_v1.4.uspp.F.UPF
co_pbe_v1.2.uspp.F.UPF
c_pbe_v1.2.uspp.F.UPF
cr_pbe_v1.5.uspp.F.UPF
cs_pbe_v1.uspp.F.UPF
cu_pbe_v1.2.uspp.F.UPF
fe_pbe_v1.5.uspp.F.UPF
f_pbe_v1.4.uspp.F.UPF
ga_pbe_v1.4.uspp.F.UPF
ge_pbe_v1.4.uspp.F.UPF
hf_pbe_plus4_v1.uspp.F.UPF
hf_pbe_v1.uspp.F.UPF
hg_pbe_v1.uspp.F.UPF
h_pbe_v1.4.uspp.F.UPF
in_pbe_v1.4.uspp.F.UPF
i_pbe_v1.uspp.F.UPF
ir_pbe_v1.2.uspp.F.UPF
k_pbe_v1.4.uspp.F.UPF
la_pbe_v1.uspp.F.UPF
li_pbe_v1.4.uspp.F.UPF
mg_pbe_v1.4.uspp.F.UPF
mn_pbe_v1.5.uspp.F.UPF
Mo_pbe_v1.uspp.F.UPF
na_pbe_v1.5.uspp.F.UPF
nb_pbe_v1.uspp.F.UPF
ni_pbe_v1.4.uspp.F.UPF
n_pbe_v1.2.uspp.F.UPF
o_pbe_v1.2.uspp.F.UPF
os_pbe_v1.2.uspp.F.UPF
pb_pbe_v1.uspp.F.UPF
pd_pbe_v1.4.uspp.F.UPF
p_pbe_v1.5.uspp.F.UPF
pt_pbe_v1.4.uspp.F.UPF
rb_pbe_v1.uspp.F.UPF
re_pbe_v1.2.uspp.F.UPF
rh_pbe_v1.4.uspp.F.UPF
ru_pbe_v1.2.uspp.F.UPF
sb_pbe_v1.4.uspp.F.UPF
sc_pbe_v1.uspp.F.UPF
se_pbe_v1.uspp.F.UPF
si_pbe_v1.uspp.F.UPF
sn_pbe_v1.4.uspp.F.UPF
s_pbe_v1.4.uspp.F.UPF
sr_pbe_v1.uspp.F.UPF
ta_pbe_v1.uspp.F.UPF
tc_pbe_v1.uspp.F.UPF
te_pbe_v1.uspp.F.UPF
ti_pbe_v1.4.uspp.F.UPF
tl_pbe_v1.2.uspp.F.UPF
v_pbe_v1.4.uspp.F.UPF
w_pbe_v1.2.uspp.F.UPF
y_pbe_v1.4.uspp.F.UPF
zn_pbe_v1.uspp.F.UPF
zr_pbe_v1.uspp.F.UPF
"""